# Generated by Django 6.0.3 on 2026-04-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0002_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
